package entidades;
// Generated 16/07/2019 06:14:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoatencion generated by hbm2java
 */
public class Tipoatencion  implements java.io.Serializable {


     private int idTipoAtencion;
     private String descrpcion;
     private Set atencions = new HashSet(0);

    public Tipoatencion() {
    }

	
    public Tipoatencion(int idTipoAtencion, String descrpcion) {
        this.idTipoAtencion = idTipoAtencion;
        this.descrpcion = descrpcion;
    }
    public Tipoatencion(int idTipoAtencion, String descrpcion, Set atencions) {
       this.idTipoAtencion = idTipoAtencion;
       this.descrpcion = descrpcion;
       this.atencions = atencions;
    }
   
    public int getIdTipoAtencion() {
        return this.idTipoAtencion;
    }
    
    public void setIdTipoAtencion(int idTipoAtencion) {
        this.idTipoAtencion = idTipoAtencion;
    }
    public String getDescrpcion() {
        return this.descrpcion;
    }
    
    public void setDescrpcion(String descrpcion) {
        this.descrpcion = descrpcion;
    }
    public Set getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set atencions) {
        this.atencions = atencions;
    }




}


